av_node:
  ros__parameters:
    publishers:
      raw_frame: /camera/raw_frame

    services:
      stop_camera: /camera/get_cam_state

    frames: 
      camera_link: camera_link
      
    rotation_angle: 0.0

    auto_exposure: Once

    resize:
      enable: False
      resized_width: 640
      resized_height: 480

    crop:
      enable: False
      cropped_width: 0
      cropped_height: 0
